---
title: "map"
author: "MelainaWright"
date: "May 26, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#answer.nb.html (can see not just the top of the data output but see entire results)

# title: "publishing"
# author: "MelainaWright"
# date: "May 26, 2017"
# output: 
#   html_document: default
#   ioslides_presentation: default
#   slidy_presentation: default

```


##Map demo
``` {r}

# 
# <!-- There are many packages that provide htmlwidgets, including: -->
# 
# <!-- dygraphs, http://rstudio.github.io/dygraphs/, for interactive time series visualisations. -->
# 
# <!-- DT, http://rstudio.github.io/DT/, for interactive tables. -->
# 
# <!-- threejs, https://github.com/bwlewis/rthreejs for interactive 3d plots. -->
# 
# <!-- DiagrammeR, http://rich-iannone.github.io/DiagrammeR/ for diagrams (like flow charts and simple node-link diagrams). -->
# 
# <!-- To learn more about htmlwidgets and see a more complete list of packages that provide them visit http://www.htmlwidgets.org/. -->



library(leaflet) #live map called openstreetmap (like google maps), runs a javascript program that runs the map, talks to a server (openstreetmap), grabs info and runs in browser; computation in browser, data sourcing from server
#leaflet is a javascript library

#creatae window and center it at lat and long and zoom by a factor, add tiles: add openstreetmap tiles, add marker to location that pops up word "maungawhau"
leaflet() %>%
  setView(174.764, -36.877, zoom = 16) %>% 
  addTiles() %>%
  addMarkers(174.764, -36.877, popup = "Maungawhau")

```